'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class add_new_person

    '''<summary>
    '''TxtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckLastName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtChineseName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtChineseName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtContactNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''checkContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkContactNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RvTxtContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RvTxtContactNo As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''TxtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RevEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RevEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''RblGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RblGender As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''CheckGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckGender As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtDateOfBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDateOfBirth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CvDateOfBirthYearOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CvDateOfBirthYearOnly As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''TxtStreetAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtStreetAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CblUserType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CblUserType As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''CvUserType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CvUserType As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''divTeacherSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTeacherSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RblRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RblRole As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''CheckRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckRole As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CblServiceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CblServiceType As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''TxtServiceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtServiceType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckTxtServiceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckTxtServiceType As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtServiceStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtServiceStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rvserviceStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvserviceStartDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RvTxtServiceStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RvTxtServiceStartDate As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''divGuardianSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGuardianSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DdlChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlChild As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CheckChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckChild As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''DdlRelationship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlRelationship As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CheckRelationship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckRelationship As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RblReligion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RblReligion As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''CheckReligion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckReligion As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BtnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SqlDataSource_Roles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Roles As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_serviceList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_serviceList As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_Children control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Children As Global.System.Web.UI.WebControls.SqlDataSource
End Class
