'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class add_new_child

    '''<summary>
    '''TxtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckLastName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtChineseName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtChineseName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckChineseName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckChineseName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RblGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RblGender As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''CheckGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckGender As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtDateOfBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDateOfBirth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckDateOfBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckDateOfBirth As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CvDateOfBirthYearOnly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CvDateOfBirthYearOnly As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''RblReligion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RblReligion As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''CheckReligion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckReligion As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtJoinedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtJoinedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckJoinedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckJoinedDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RvTxtJoinedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RvTxtJoinedDate As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''TxtInviter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtInviter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtChurch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtChurch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtSchool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSchool As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtRemark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancel As Global.System.Web.UI.WebControls.Button
End Class
